" base config {{{
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set guicursor=a:block
set nocompatible 	" not vi compatible
set shortmess+=sI 	" Disable the default Vim startup message
set noerrorbells visualbell t_vb=   " Disable audible bell

filetype on         " enable file type detection,
filetype indent on	" use corresponding indent
filetype plugin on	" set load plugin by file type
syntax enable		" highlight enable
syntax on  			" highlight auto
set t_Co=256        " use 256 colors

set cursorline		" highlight current line

set number   		" enable line number
set relativenumber 	" relative line number

" status line
set laststatus=2  	" always show the status line at the buttom

set backspace=indent,eol,start 	" allow backspacing over everything
set whichwrap+=h,l  " set the cursor keys across rows
set matchpairs+=<:> " allow % jump between <>
" set background=dark " set background color

set termguicolors
hi Normal guibg=NONE ctermbg=NONE
hi NonText guibg=NONE ctermbg=NONE
hi LineNr guibg=NONE ctermbg=NONE
hi SignColumn guibg=NONE ctermbg=NONE
hi Folded guibg=NONE ctermbg=NONE
hi EndOfBuffer guibg=NONE ctermbg=NONE


set mouse+=a        " Enable mouse support
" open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright
let mapleader=" "
let maplocalleader=","
" having longer updatetime brings noticable delays and poor user experience
set updatetime=100
" Always show the signcolumn(the margin in the left), otherwise it would shift
" the text each time diagnostics appear/become resolved(coc)
set signcolumn=yes
set showmatch
set matchtime=1
" }}}


" edit config {{{
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set showcmd 		" display inputting commands
set autoindent 		" copy indent from current line when starting a new line

" show indent line, it looks annoying
" set list
" set listchars=tab:\ \ ,leadmultispace:┊\ \ \ ,multispace:\ \

set tabstop=4       " the size of tab
set expandtab		" replace tab with spaces
set softtabstop=4	" 1 tab == 4 spaces
set shiftwidth=4	" shift size when using '<<' or '>>'
set shiftround      " round indent to multiple of 4

set textwidth=80    " the width of each line
set wrap            " break lines automatically
set linebreak       " break only when encountering with specific character
set scrolloff=5
" match ErrorMsg '\%>80v.\+'	" highlight the characters above 80

set undofile                " create undo file
set undodir=~/.vim/.undo//
set history=50              " record 100 operations

set timeoutlen=500  " so the <esc>O won't delay for long

" When editing a new file, save it automatically.
" 1. The event to watch for
" 2. A pattern to filter the event. For example: *.txt
" 3. The command to run
" Do it in this way to avoid adding dupicate autocmds every time we source vimrc
augroup writeNewFile
    autocmd!
    autocmd BufNewFile * :w
augroup END

" fold vim codes using 'za', use 'zf' + motion or in visual mode
" to create folds on the object
augroup fold_vimscript
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

set foldlevelstart=0        " start with all folds closed
" }}}


" search config {{{
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" ==# is the 'case-sensitive no matter what the user has set'
" ==? is the 'case-insensitive no matter what the user has set'
set ignorecase 		" Now, 'foo' == 'FOO' is true!. But ==# still works
set smartcase 	    " ignore case when lowercase letter only
set incsearch 		" searching as you type
set nohlsearch      " nohighlight after search

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" cache and buffer config
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nobackup                " don't create backup file
set nowritebackup           " No backup made
set noswapfile              " don't create temp file

set autochdir               " change directory when open a new file
set autoread                " when editing files are changed in other place
set hidden 			        " enable to hidden buffers without saving

" wildchar is <TAB> by default
set wildmenu
set wildmode=longest,list

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" encode config
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set langmenu=zh_CN.UTF-8    " set language menu encode utf8
set helplang=cn             " set helping language Chinese
" }}}


" binding config {{{
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Use jk to escape insert mode
inoremap jk <esc>

" Use some key mappings to compile and run quickly
" In these files, when I press <tab>, it complies and runs automatically,
" I don't know which plugin works. But it's convenient. It works like <C-i>
autocmd FileType cpp nnoremap R :w<CR>:!g++ -std=c++20 % -o %<<CR>:!./%<<CR>
autocmd FileType c nnoremap R :w<CR>:!gcc % -o %<<CR>:!./%<<CR>
autocmd FileType python nnoremap R :w<CR>:!python3 %<CR>
" It doesn't work
" autocmd FileType markdown nnoremap R :InstantMarkdownPreview<CR>

" Have j and k navigate visual lines in normal mode
nnoremap <silent> <Plug>RealJ j
nnoremap <expr> j (v:count > 0) ? '<Plug>RealJ' : 'gj'
nnoremap <silent> <Plug>RealK k
nnoremap <expr> k (v:count > 0) ? '<Plug>RealK' : 'gk'

nnoremap S :w<CR>
nnoremap Q :q<CR>

" Use C-w, C-l to delete a word/letter in insert mode and cmd-line mode
inoremap <C-w> <esc>lcb
inoremap <C-h> <Backspace>
inoremap <C-a> <Home>
inoremap <C-e> <End>
inoremap <C-f> <Right>
inoremap <C-b> <Left>

" find next placeholder(<++>) and edit it
nnoremap <leader><leader> /<++><CR>c4l

" change window size
nnoremap <C-h> <C-w><
nnoremap <C-j> <C-w>-
nnoremap <C-k> <C-w>+
nnoremap <C-l> <C-w>>

" shift between windows
nnoremap <S-h> <C-w>h
nnoremap <S-j> <C-w>j
nnoremap <S-k> <C-w>k
nnoremap <S-l> <C-w>l

" shift between buffers
" 'bn', 'bp' will make b very slow
" 'nb', 'pb' will make n, p very slow
nnoremap <leader>n :bn<CR>
nnoremap <leader>p :bp<CR>
nnoremap <leader>x :bd<CR>

" " edit .vimrc when editing other files
" autocmd FileType python nnoremap <C-i> :!python3 %<CR>
" nnoremap <leader>vim :e $MYVIMRC<CR>
" nnoremap <leader>rc :vsp $MYVIMRC<CR>
" " source my .vimrc
autocmd FileType vim nnoremap <leader>sv :w <CR> :source $MYVIMRC<CR>
" " install and clean plugins
autocmd FileType vim nnoremap <leader>in :PlugInstall<CR>
autocmd FileType vim nnoremap <leader>cl :PlugClean<CR>
" }}}


" plugins config {{{
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'      " <C-n>, directory overview
Plug 'jiangmiao/auto-pairs'
" vim themes
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'vim-airline/vim-airline'
Plug 'easymotion/vim-easymotion'		" move as fast as you want!
Plug 'vim-python/python-syntax', {'for': 'py'}  " python syntax highlight
" Plug 'Yggdroot/LeaderF', {'do': ':LeaderfInstallCExtension'}    " search file
Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'chxuan/prepare-code'
" change surround quickly
Plug 'tpope/vim-surround'
" add comments quickly
Plug 'tpope/vim-commentary'
" cpp highlight
" loaded when a file with specific file type is opened
Plug 'octol/vim-cpp-enhanced-highlight', {'for': 'cpp'}
" enhance f/t
Plug 'rhysd/clever-f.vim'
" colorful parenthesis
Plug 'frazrepo/vim-rainbow'
" shows git diff in the column. it shows which lines have been added, deleted,
" modified and so on
Plug 'airblade/vim-gitgutter'
" display indent 'block'
Plug 'preservim/vim-indent-guides'
" it doesn't work
Plug 'instant-markdown/vim-instant-markdown'
call plug#end()

" LeaderF settings {{{
" let g:Lf_ShortcutF = '<C-p>'
" }}}


" Nerdtree Settings {{{
" Press tt to show or hide the nerd tree
nnoremap tt :NERDTreeToggle<CR>
let g:NERDTreeFileExtensionHighlightFullName = 1
let g:NERDTreeExactMatchHIghlightFullName = 1
let g:NERDTreePatternMatchHighlightFullName = 1
let g:NERDTreeHighlightFoldersFullName = 1
let g:NERDTreeDirArrowExpandable='▷'
let g:NERDTreeDirArrowCollapsible='▼'
let g:NERDTreeWinSize = 18
" }}}


" airline, catppuccin settings {{{
let g:airline_theme = 'catppuccin_mocha'
let g:airline_powerline_fonts = 1
let g:airline_extensions = ['tabline', 'coc', 'branch']
" |A|B|     C       X|Y|Z|[...]
let g:airline_section_b = '%n'              " buffer number
let g:airline_section_c = '%F'              " full file name
let g:airline_section_x = '%h'              " help buffer flag
let g:airline_section_y = '%y'              " filetype
let g:airline_section_z = '%p%% ≡ %l/%L %c' " percentage, row, Row, column
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
" let g:tokyonight_style = 'night'
" let g:tokyonight_transparent_background = 1     " trasparent background
" let g:tokyonight_enable_italic = 0              " non-italic text
" let g:tokyonight_disable_italic_comment = 0     " italic comment
colorscheme catppuccin_mocha
" }}}


" easymotion settings {{{
let g:EasyMotion_smartcase = 1
map <Leader> <Plug>(easymotion-prefix)
" based on word
nnoremap <leader>w <Plug>(easymotion-bd-w)
" Based on two characters
nnoremap <leader>s <Plug>(easymotion-s2)
" It looks nice, but when the contents are folded, it can find them
" nnoremap / <Plug>(easymotion-sn)
" onoremap / <Plug>(easymotion-tn)
" nnoremap n <Plug>(easymotion-next)
" nnoremap N <Plug>(easymotion-prev)

" }}}


" it seems that I can do these with key-mapping
let g:surround_no_insert_mappings=1
" verb(cs, ds, ys) + scope + object(open parenthesis has one more whitespace)
" }}}


" coc.nvim settings {{{
" Use <CR> to accept selected completion item
" Use tab, S-tab to select next, previous completion
" Use <C-a> to trigger completion
inoremap <expr><C-n> coc#pum#visible() ? coc#pum#next(1) :
      \ coc#refresh()
inoremap <expr><C-p> coc#pum#visible() ? coc#pum#prev(1) :
      \ coc#refresh()
" inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
inoremap <silent><expr> <C-y> coc#pum#visible() ? coc#pum#confirm() :
      \ coc#refresh()

" CheckBackspace{{{
function! CheckBackspace() abort
    let col = col('.') - 1            " cursor_pos--
    " if cursor is the start of the line
    " or the char before it is whitespace
    " or it's the end of the line
    return !col || getline('.')[col - 1]  =~# '\s' || col >= len(getline('.'))
endfunction
"}}}

" Use ' -' and ' =' to navigate diagnostics
" ' a' to show all diagnostics
nnoremap <silent> <leader>- <Plug>(coc-diagnostic-prev)
nnoremap <silent> <leader>= <Plug>(coc-diagnostic-next)
nnoremap <silent> <leader>a :<C-u>CocList diagnostics<CR>
" Goto code navigation
nnoremap <silent> gd <Plug>(coc-definition)
nnoremap <silent> gt <Plug>(coc-type-definition)
nnoremap <silent> gi <Plug>(coc-implementation)
nnoremap <silent> gr <Plug>(coc-references)
" Use D to show documentation in preview window
nnoremap <silent> <leader>d :call ShowDocumentation()<CR>
function! ShowDocumentation()
    if CocAction('hasProvider', 'hover')
        call CocActionAsync('doHover')
    else
        call feedkeys('K', 'in')
    endif
endfunction
" Symbol renaming
nnoremap <leader>rn <Plug>(coc-rename)
" Applying codeAction to the selected region
" Maybe I need some plugins to use these two lines
function! CocActionOpenFromSelected(type) abort
    execute 'CocCommand actions.open ' . a:type
endfunction
xnoremap <silent> <leader>a :<C-u>execute 'CocCommand actions.open ' .visualmode()<CR>
nnoremap <silent> <leader>a :<C-u>set operatorfunc=<SID>CocActionOpenFromSelected<CR>g@
" }}}


" vim-rainbow settings {{{
let g:rainbow_active = 1
"}}}


" vim-gitgutter settings {{{
" jump between hunks(hunk: a contiguous block of changes between two versions)
nnoremap ]h <Plug>(GitGutterNextHunk)
nnoremap [h <Plug>(GitGutterPrevHunk)
" }}}


" python highlight{{{
let g:python_highlight_all = 1
"}}}


" indent-guide {{{
let g:indent_guides_enable_on_vim_startup = 1   " auto enable
let g:indent_guides_start_level = 2             " start in the second level
let g:indent_guides_guide_size = 1              " the width of the bar
" }}}


" vim-instant-markdown {{{
" execute   `:h vim-instant-markdown-configuration` to read about configurations
let g:instant_markdown_slow = 1         " no real-time refresh
let g:instant_markdown_autostart = 1    " auto launch when open markdown file
let g:instant_markdown_browser = "chrome --new-window"
let g:instant_markdown_autoscroll = 1   " auto scrools to where cursor is
let g:instant_markdown_theme = 'dark'

" }}}

let &t_ti .= "\e[2 q""]"
let &t_te .= "\e[0 q""]"
" }}}
" new line
